version: "3"
services:
  api-server:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm install && npm run dev"

  mongo-db:
    container_name: mongo-database
    image: mongo
    ports:
      - "27017:27017"